spring.application.name=sistema-clima
server.port=8080

# ==========================================
# DB - Configuración dinámica (Nube : Local)
# ==========================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/climatizacion_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA
# ==========================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# Frontend
# ==========================================
frontend.url=${FRONTEND_URL:http://localhost:5500}

# ==========================================
# OPTIMIZACIÓN Y LIMPIEZA DE LOGS
# ==========================================
spring.jpa.open-in-view=false
spring.thymeleaf.check-template-location=false

# ==========================================
# Cloudinary (para imágenes)
# ==========================================
cloudinary.url=${CLOUDINARY_URL:cloudinary://368586771746547:iuc6LAjn6ftlMULMjAOvdzNgVaA@doq0aezh4}

resend.api.key=${RESEND_API_KEY:dummy_key_for_local_development}

# JWT Config
jwt.secret=+T/u5wL9n5f2G7kE3vR8wJ6tX4bH2mP9sL1kD5fG7hJ3=
jwt.expiration=86400000

# Tamaño máximo de archivo (subida de fotos y firmas)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB